# Generated by Django 5.2.1 on 2025-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.IntegerField(max_length=20)),
                ('employeeId', models.CharField(max_length=10, unique=True)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
