# Generated by Django 5.2.1 on 2025-05-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='role',
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
