# Generated by Django 5.2.1 on 2025-05-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_registereduser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('HR', 'HR')], default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='employeeId',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
