# Generated by Django 5.2.1 on 2025-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_registereduser_role_alter_registereduser_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='employeeId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='registereduser',
            constraint=models.UniqueConstraint(condition=models.Q(('employeeId', None), _negated=True), fields=('employeeId',), name='unique_employee_id_not_null'),
        ),
    ]
