# Generated by Django 5.2.1 on 2025-05-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_registereduser_employeeid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registereduser',
            name='unique_employee_id_not_null',
        ),
        migrations.AddConstraint(
            model_name='registereduser',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('employeeId__isnull', True), _negated=True), models.Q(('employeeId', ''), _negated=True)), fields=('employeeId',), name='unique_employee_id_not_null'),
        ),
    ]
