# Generated by Django 5.2.1 on 2025-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_registereduser_unique_employee_id_not_null_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('jobType', models.CharField(max_length=100)),
                ('employmentType', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship'), ('TM', 'Temporary')], max_length=2)),
                ('location', models.CharField(max_length=128)),
                ('openings', models.IntegerField()),
                ('lastApplyDate', models.DateField()),
                ('requiredSkills', models.CharField(max_length=255)),
            ],
        ),
    ]
