# Generated by Django 5.2.1 on 2025-05-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employmentType',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='jobType',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
