# Generated by Django 5.2.1 on 2025-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_application_score_alter_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.IntegerField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
