# Generated by Django 5.2.1 on 2025-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_application_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
