# Generated by Django 5.2.1 on 2025-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_application_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
