# Generated by Django 5.2.1 on 2025-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_application_applied_at_alter_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
