# Generated by Django 5.2.1 on 2025-05-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_application_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
